project:
  type: website

website:
  favicon: images/hex.png
  title: " | Núcleo de Innovación Social"
  image: images/hex.png

  page-footer:
    left: "&copy; 2025 Betsabé Cohen & Ariana Bardauil"
    right: "Website construida con [Quarto](https://quarto.org/)."
    
  navbar:
    background: primary
    logo: "images/logoNIS.png"
    search: true
    
    right:
      - href: index.qmd
        text: INICIO
      - href: charlas.qmd
        text: CHARLAS
      - href: proyectos.qmd
        text: PROYECTOS
      - href: about.qmd
        text: NOSOTROS
      - href: contacto.qmd
        text: CONTACTO
    tools:
      - icon: linkedin
        href: "https://www.linkedin.com/company/nucleois"
      - icon: instagram
        href: "https://www.instagram.com/nucleodeinnovacion/"

 

format:
  html:
    theme:  flatly 
    css: styles.css
    toc: false

editor: visual

