project:
  type: website

website:
  favicon: images/hex.png
  title: " | Núcleo de Innovación Social"
  image: images/hex.png

  page-footer:
    left: "&copy; 2025 Betsabé Cohen & Ariana Bardauil"
    right: "Website construida con [Quarto](https://quarto.org/)."
    center:
      - href: https://github.com/nucleodeinnovacion
        icon: github
        aria-label: GitHub
      - href: https://www.linkedin.com/company/nucleois
        icon: linkedin
        aria-label: LinkedIn
      - href: https://www.instagram.com/nucleodeinnovacion/
        icon: instagram
        aria-label: Twitter/X
      - text: "info@nucleodeinnovacion.com"


   
    
  navbar:
    background: primary
    logo: "images/logoNIS.png"
    search: true
    
    right:
      - href: index.qmd
        icon: house-door-fill
        text: " "
      - text: ¿Quienes somos? 
        menu:
          
        - href: institucional.qmd
          text: Nuestros pilares
          
        - href: about.qmd
          text: Nuestra Historia
        
        - href: equipo.qmd
          text: Equipo
          
      - text: ¿Qué hacemos?
        menu:
        - href: charlas.qmd
          text: Charlas y Talleres
        - href: proyectos.qmd
          text: Proyectos

      - href: cursos.qmd
        text: Cursos

      - href: blog.qmd
        text: Blog
        
      - href: contacto.qmd
        text: Contactanos


 

format:
  html:
    theme:  flatly 
    css: styles.css
    toc: false

editor: visual

