---
title: "Nuestra historia"
css: presenta.css
---

El **Núcleo de Innovación Social (NIS)** comenzó como un laboratorio de tecnología social en 2017, gracias a la colaboración entre la **Comisión Interinstitucional de Ciencia y Tecnología del Colegio de Sociólogos de la Provincia de Buenos Aires**, el **Consejo de Profesionales de Sociología** y la **Asociación de Sociólogos y Sociólogas de la República Argentina**.

En sus inicios, el NIS se centró en conectar a los profesionales de la sociología involucrados en tecnología y en organizar jornadas de programación. Con el tiempo, el laboratorio se consolidó, expandiendo su campo de acción hacia áreas estratégicas como **Ciencia de Datos**, **Inteligencia Artificial**, **Diseño de Experiencias** y **Cripto Tecnologías**.

Una característica distintiva del NIS es su **estructura descentralizada**, lo que permite una mayor flexibilidad y colaboración entre diferentes actores. Este enfoque innovador y colaborativo continúa marcando la diferencia en todos nuestros proyectos.

::: card2
## El NIS en el tiempo

Nació en 2017 como un esfuerzo colaborativo entre la **Comisión Interinstitucional de Ciencia y Tecnología del Colegio de Sociólogos de la Provincia de Buenos Aires**, el **Consejo de Profesionales de Sociología** y la **Asociación de Sociólogos y Sociólogas de la República Argentina**.

Desde su creación, el NIS se ha enfocado en promover la integración de las **ciencias sociales** con las **tecnologías emergentes**, buscando crear soluciones innovadoras que aborden los problemas más complejos de nuestra sociedad.

A lo largo de los años, el NIS ha evolucionado para convertirse en un referente en áreas clave como **Ciencia de Datos**, **Inteligencia Artificial**, **Diseño de Experiencias** y **Cripto Tecnologías**. Nos enorgullece ser un espacio descentralizado que fomenta el trabajo interdisciplinario, facilitando la colaboración entre profesionales de diversas áreas y disciplinas.

Hoy en día, el NIS continúa impulsando el intercambio de conocimientos y la cooperación entre la **tecnología** y las **ciencias sociales**. Nuestro objetivo es generar nuevas preguntas y respuestas para los desafíos contemporáneos, utilizando la innovación social como motor de cambio.
:::
